FROM python:3.9-slim

# Install build dependencies
RUN apt-get update && \
    apt-get install -y gcc libffi-dev && \
    apt-get clean

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY broadcaster.py .

CMD ["python", "broadcaster.py"]