FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y gcc libffi-dev && \
    apt-get clean

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/web_server/web_server.py .

# Add a simple health check
HEALTHCHECK CMD curl --fail http://localhost:8000/ || exit 1

CMD ["python", "web_server.py"]